using System.Collections;
using System.Collections.Generic;
using UnityEngine;
 
[ExecuteAlways] // Editorç¹§è²†é€•æº˜ï¼ ç¸ºï½¦ç¸º„ãâ†‘ç¸ºä¸Šâ€»ç¹§ã‚‡ï½®æº¯ï½¡å¾Œã€’ç¸ºé˜ªï½‹
public class AspectKeeper : MonoBehaviour
{
    [SerializeField]
    private Camera targetCamera; //èŸ‡ï½¾é›ï½¡ç¸ºï½¨ç¸ºå¶ï½‹ç¹§ï½«ç¹ï½¡ç¹ï½©

    [SerializeField]
    private Vector2 aspectVec; //é€¶ï½®é€§„èï½§ï½£èœ’ä¸ï½ºï½¦

    void Update()
    {
        var screenAspect = Screen.width / (float)Screen.height; //é€•ï½»é«±ï½¢ç¸ºï½®ç¹§ï½¢ç¹§ï½¹ç¹å£¹ã‘ç¹åŸŸï½¯”
        var targetAspect = aspectVec.x / aspectVec.y; //é€¶ï½®é€§„ã®ç¹§ï½¢ç¹§ï½¹ç¹å£¹ã‘ç¹åŸŸï½¯”

        var magRate = targetAspect / screenAspect; //é€¶ï½®é€§„ãã„ç¹§ï½¹ç¹å£¹ã‘ç¹åŸŸï½¯æ–â†“ç¸ºå¶ï½‹ç¸ºæº˜ï½ç¸ºï½®è›Ÿå’²ç´«

        var viewportRect = new Rect(0, 0, 1, 1); //Viewportè›»æ™„æ‚„è›Ÿï½¤ç¸ºï½§Rectç¹§å‰ƒï½½æ‡ˆˆ

        if (magRate < 1)
        {
            viewportRect.width = magRate; //è´ï½¿é€•ï½¨ç¸ºå¶ï½‹è®“ï½ªèŸ·…ãï½’èŸç”»å³©
            viewportRect.x = 0.5f - viewportRect.width * 0.5f;//è³ï½­èŸï½®èŸ‡„ãâ—‹
        }
        else
        {
            viewportRect.height = 1 / magRate; //è´ï½¿é€•ï½¨ç¸ºå¶ï½‹é‚µï½¦èŸ·…ãï½’èŸç”»å³©
            viewportRect.y = 0.5f - viewportRect.height * 0.5f;//è³ï½­èŸï½®è´å’å‡½
        }

        targetCamera.rect = viewportRect; //ç¹§ï½«ç¹ï½¡ç¹ï½©ç¸ºï½®Viewportç¸ºï½«é©•ï½©é€•ï½¨
    }
}
